[package]
name = "streamlink-twitch-gui"
version = "0.1.0"
description = "Desktop Twitch browser for Streamlink"
authors = ["Wibias"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "streamlink_twitch_gui_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
keyring = "4.1.5"
url = "2.5.8"
uuid = { version = "1.24.0", features = ["v4"] }
sha2 = "0.11.0"
base64 = "0.23.0"
rand = "0.10.2"
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "sync", "time", "net", "process", "io-util"] }
tiny_http = "0.12.0"
reqwest = { version = "0.13.4", default-features = false, features = ["json", "rustls", "form"] }
tauri-plugin-store = "2.4.4"

