codecov:
    notify:
        require_ci_to_pass: yes
comment:
  layout: "reach, diff, flags, files"
  after_n_builds: 999999999
coverage:
    range: "0..100"
    round: down
    precision: 2
    status:
        changes: no
        patch: yes
        project:
            default: no
            app:
                target: 50
                threshold: 1
                paths:
                    - "!src/test/"
            tests:
                target: 99
                threshold: 0
                paths:
                    - "src/test/"
parsers:
    javascript:
        enable_partials: yes
